// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmJ631WzrGujK2lFJIpf6r-4WQhKdHKT0',
    appId: '1:36393273186:web:e4ef7aad27eccad50ace3b',
    messagingSenderId: '36393273186',
    projectId: 'recipe-application-ed080',
    authDomain: 'recipe-application-ed080.firebaseapp.com',
    storageBucket: 'recipe-application-ed080.appspot.com',
    measurementId: 'G-MJRMWNBBN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6GMaTVNUewoTw5zGJlO64H9sJevbwA88',
    appId: '1:36393273186:android:f51b6108dd6ceb200ace3b',
    messagingSenderId: '36393273186',
    projectId: 'recipe-application-ed080',
    storageBucket: 'recipe-application-ed080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZSTramm-rrsirLQwCKlsg6nzp5bR5vw',
    appId: '1:36393273186:ios:95131a789820ced60ace3b',
    messagingSenderId: '36393273186',
    projectId: 'recipe-application-ed080',
    storageBucket: 'recipe-application-ed080.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZSTramm-rrsirLQwCKlsg6nzp5bR5vw',
    appId: '1:36393273186:ios:95131a789820ced60ace3b',
    messagingSenderId: '36393273186',
    projectId: 'recipe-application-ed080',
    storageBucket: 'recipe-application-ed080.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmJ631WzrGujK2lFJIpf6r-4WQhKdHKT0',
    appId: '1:36393273186:web:968e14de86ff0de10ace3b',
    messagingSenderId: '36393273186',
    projectId: 'recipe-application-ed080',
    authDomain: 'recipe-application-ed080.firebaseapp.com',
    storageBucket: 'recipe-application-ed080.appspot.com',
    measurementId: 'G-8Q3G06RZC2',
  );
}
